GET http://localhost/apigps/api/cliente.php

###
GET http://localhost/apigps/api/cliente.php?id=1

###
POST http://localhost/apigps/api/cliente.php
content-type: application/json


{
    "rutC": "20133132-2",
    "emailC": "pantruka@gaymail.com",
    "nombreC": "Pantruka",
    "apellidoC": "Pantrukey",
    "direccionC": "null",
    "cComuna": 1107
}

### 
GET http://localhost/apigps/apigps/api/trabajo.php

###

GET http://localhost/apigps/apigps/api/trabajo.php?cTrabajo=1

###
POST http://localhost/apigps/apigps/api/trabajo.php
content-type: application/json

{
    "nombreTrabajo": "aaa",
    "descripcionTrabajo": "asdasd",
    "fechaEstimadaT": "2022-06-01",
    "fechaRealT": "2022-05-12",
    "costoT": 20000,
    "horasT": 40,
    "cOrdenTrabajo": 1,
    "cTipoT": 1,
    "cEmpleado": 1,
    "cTipoE": 1


}
###
DELETE http://localhost/apigps/apigps/api/trabajo.php
content-type: application/json

{
    "cTrabajo": 3

}
###