GET http://localhost/apigps/api/cliente.php

###

GET http://localhost/apigps/api/cliente.php?id=1

###
POST http://localhost/apigps/api/cliente.php
content-type: application/json

{
    "rutC": "20133132-2",
    "emailC": "pantruka@gaymail.com",
    "nombreC": "Pantruka",
    "apellidoC": "Pantrukey",
    "direccionC": "null",
    "cComuna": 1107
}

