GET http://localhost:8080/apigps/api/cliente.php

###
GET http://localhost:8080/apigps/api/cliente.php?id=1

###
POST http://localhost:8080/apigps/api/cliente.php



###
GET http://localhost:8080/apigps/api/comuna.php






