GET http://localhost:8080/apigps/api/cliente.php

###
POST http://localhost:8080/apigps/api/cliente.php

 {
    "rutC": "19944560k",
    "emailC": "aaa@BBB.CL",
    "nombreC": "PABLO",
    "apellidoC": "ANTUA",
    "direccionC": "mi casa XXX",
    "estadoC": 0,
    "cComuna": 1107
  }