###CONSULTAR POR CODIGO INSUMO
GET http://localhost/APIGPS/apigps/api/insumo.php

###AGREGAR INSUMO

POST http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "AAAAAAAAAAAAAA",
    "cantidad": "15",
    "costo": 39900,
    "cInsumo":1,
    "estado": 1
}
###AGREGAR INSUMO

POST http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "BBBBBBBBBBBBB",
    "cantidad": "15",
    "costo": 39900,
    "cInsumo":1,
    "estado": 1
}
###AGREGAR INSUMO

POST http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "CCCCCCCCCCCC",
    "cantidad": "15",
    "costo": 39900,
    "cInsumo":1,
    "estado": 1
}
###AGREGAR INSUMO

POST http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "DDDDDDDDDDDD",
    "cantidad": "15",
    "costo": 39900,
    "cInsumo":1,
    "estado": 1
}
###AGREGAR INSUMO

POST http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "EEEEEEEEEEE",
    "cantidad": "15",
    "costo": 39900,
    "cInsumo":1,
    "estado": 1
}

###

PUT http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "BBBBBBBBBBB",
    "cantidad": 1000000,
    "costo": 90000,
    "cInsumo":88
}

###DELETE

DELETE http://localhost/APIGPS/apigps/api/insumo.php

{
    "cInsumo":89

}