###CONSULTAR POR CODIGO INSUMO
GET http://localhost/APIGPS/apigps/api/insumo.php?cTaller=1


###AGREGAR INSUMO

POST http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "AAAAAAAAAAAAAA",
    "cantidad": "15",
    "costo": 39900,
    "cInsumo":1,
    "estado": 1
}

###

PUT http://localhost/APIGPS/apigps/api/insumo.php

{
    "nombreInsumo": "BBBBBBBBBBB",
    "cantidad": 1000000,
    "costo": 90000,
    "cInsumo":128,
    "cTaller":1
}

###DELETE

DELETE http://localhost/APIGPS/apigps/api/insumo.php

{
    "cInsumo":137

}