POST http://localhost/apigps/api/usuario.php

{
    "nombreU": "Richard Calbullanca",
    "email": "r@r.cl",
    "clave": "1234"
    "cRolU": 3,
    "cTaller": 1,
    
}

###

GET http://localhost/apigps/api/usuario.php?cTaller=1