GET http://localhost/apigps/api/vehiculo.php

###

GET http://localhost/apigps/api/vehiculo.php?cVehiculo=5

###

POST http://localhost/apigps/api/vehiculo.php

{
    "patenteV": "XXXXXX",
    "modeloV": "CAMAAAAION",
    "colorV": "EEEEE",
    "estadoV": "FFFF",
    "estadoRevisionTecnicaV": "AAA",
    "montoAseguradora": 123123,
    "cCliente": 2,
    "cAseguradora": null,
    "cTipoCarroceria": null
}
